apiVersion: v1
kind: Service
metadata:
        name: mysql-docker-container
spec:
        ports:
                - port: 3306
                  protocol: TCP
        selector:
                app: mysql-docker-container
---
apiVersion: v1
kind: Service
metadata:
        name: worker
spec:
        ports:
                - name: rasa
                  protocol: TCP
                  port: 5005
                - name: actions
                  protocol: TCP
                  port: 5055
---
apiVersion: v1
kind: Service
metadata:
        name: webui
spec:
        type: NodePort
        ports:
                - port: 80
                  targetPort: 80
                  nodePort: 30088
        selector:
                app: webui
