version: "2"

services:
  webui:
    build: webui
    ports:
    - "80:80"
    volumes:
    - "./webui/files/:/files/"

  #database               
        mydb:
                restart: always
                container_name: sql
                image: mysql
                environment:
                        MYSQL_ROOT_PASSWORD: notpassword
                        MYSQL_ROOT_HOST: '%'
                        MYSQL_DATABASE: campus
                ports:
                        - "3000:3000"
                volumes:
                        - mysql:/var/lib/mysql
                        - mysql_config:/etc/mysql
volumes:
        mysql:
        mysql_config: 
