version: '3'

services:
#webui
        webui:
                build: webui
                image: cloudChat/webui
                container_name: webui
                volumes:
                        - ./webui/logs:/var/logs
                restart: unless-stopped
                ports:
                        - "80:80"
                        - "443:443"
#database               
        mydb:
                restart: always
                container_name: mysql-docker-container
                image: mysql
                environment:
                        MYSQL_ROOT_PASSWORD: cloudroot
                        MYSQL_ROOT_HOST: 'cloud'
                        MYSQL_DATABASE: CloudChat
                ports:
                        - "3308:3306"
                volumes:
                        - mysql:/var/lib/mysql
                        - mysql_config:/etc/mysql
volumes:
        mysql:
        mysql_config: 
