version: "3"

services:
  webui:
    build: webui
    image: 127.0.0.1:30000/webui:v0.1
    ports:
    - "8000:80"

  database:
    image: sql

  worker:
    build: worker
    image: 127.0.0.1:30000/worker:v0.1
    deploy:
      replicas: 10
