apiVersion: v1
kind: Service
metadata:
  name: webui
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30088
  selector:
    app: webui

---

apiVersion: v1 
kind: Service 
metadata:  
  name: database 
spec:  
  ports:    
    - port: 6379      
      protocol: TCP      
      targetPort: 6379  
  selector:    
      app: database
 
---
