apiVersion: apps/v1
kind: Deployment
metadata:
        name: mysql-docker-container
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: mysql-docker-container
        strategy:
                type: Recreate
        template:
                metadata:
                        labels:
                                app: mysql-docker-container
                spec:
                        containers:
                                - image: mysql:latest
                                  name: mysql-docker-container
                                  env:
                                          - name: MYSQL_ROOT_PASSWORD
                                            valueFrom: 
                                                secretKeyRef:
                                                    name: mysql-secret
                                                    key: cloudroot
                                          - name: MYSQL_DATABASE
                                            value: CloudChat
                                  ports:
                                          - containerPort: 3306
                                  volumeMounts:
                                          - name: sql-storage
                                            mountPath: /var/lib/mysql
                        volumes:
                                - name: mysql-persistent-storage
                                  persistentVolumeClaim:
                                          claimName: mysql-pvc
---                                          
apiVersion: apps/v1
kind: Deployment
metadata:
        name: worker
spec:
        replicas: 1
        selector:
                matchLabels:
                        app: worker
        template:
                metadata:
                        labels:
                                app: worker
                spec:
                        containers:
                                - name: worker-rasa
                                  image: 155.98.37.40/chatbot-rasa:0.3
                                  ports:
                                          - containerPort: 5005
                                - name: worker-actions
                                  image:155.98.37.40/worker-actions:0.1
                                  ports:
                                          - containerPort: 5055
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webui
spec:
  selector:
    matchLabels:
      app: webui
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: webui
    spec:
      containers:
      - name: webui
        image: 155.98.37.40/webui:0.1
        ports:
        - containerPort: 80
