apiVersion: apps/v1
kind: Deployment
metadata:
  name: sql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sql
  template:
    metadata:
      labels:
        app: sql
    spec:
      containers:
      - name: sql
        image: sql
        ports:
          - name: http-port
            containerPort: 3000
